/*
SQLyog Ultimate v10.00 Beta1
MySQL - 5.5.51 : Database - survey0315_log
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`survey0315_log` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `survey0315_log`;

/*Table structure for table `survey_log_2018_09` */

DROP TABLE IF EXISTS `survey_log_2018_09`;

CREATE TABLE `survey_log_2018_09` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPERATOR` varchar(255) DEFAULT NULL,
  `OPERATE_TIME` varchar(255) DEFAULT NULL,
  `METHOD_NAME` varchar(255) DEFAULT NULL,
  `TYPE_NAME` varchar(255) DEFAULT NULL,
  `PARAMS` varchar(8000) DEFAULT NULL,
  `RETURN_VALUE` varchar(8000) DEFAULT NULL,
  `EXCEPTION_TYPE` varchar(255) DEFAULT NULL,
  `EXCEPTION_MESSAGE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `survey_log_2018_09` */

/*Table structure for table `survey_log_2018_10` */

DROP TABLE IF EXISTS `survey_log_2018_10`;

CREATE TABLE `survey_log_2018_10` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPERATOR` varchar(255) DEFAULT NULL,
  `OPERATE_TIME` varchar(255) DEFAULT NULL,
  `METHOD_NAME` varchar(255) DEFAULT NULL,
  `TYPE_NAME` varchar(255) DEFAULT NULL,
  `PARAMS` varchar(8000) DEFAULT NULL,
  `RETURN_VALUE` varchar(8000) DEFAULT NULL,
  `EXCEPTION_TYPE` varchar(255) DEFAULT NULL,
  `EXCEPTION_MESSAGE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `survey_log_2018_10` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
